// Command licensesdoc maintains the generated Go-module section of
// THIRD_PARTY_LICENSES.md from a go-licenses CSV report.
//
// Usage:
//
//	go run github.com/google/go-licenses@v1.6.0 report ./cmd/ovumcy | go run ./scripts/licensesdoc -write
//	go run github.com/google/go-licenses@v1.6.0 report ./cmd/ovumcy | go run ./scripts/licensesdoc -check
//
// -write rewrites the block between the BEGIN/END markers in place; -check
// exits non-zero when the committed block differs from what the report on
// stdin generates, printing which rows diverged. CI runs the -check form, so a
// dependency change that lands without regenerating the inventory fails the
// build rather than silently un-truing the file's completeness claim.
//
// The transform is deliberately deterministic across platforms: go-licenses
// emits OS-native path separators inside license URLs, so every backslash in
// the URL column is normalized to a forward slash before the rows are sorted.
package main

import (
	"bufio"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
)

const (
	inventoryPath = "THIRD_PARTY_LICENSES.md"
	beginMarker   = "<!-- BEGIN GO MODULE LICENSES (generated by scripts/licensesdoc; do not edit by hand) -->"
	endMarker     = "<!-- END GO MODULE LICENSES -->"
	// ownModule's row reports the application's own license, which the file's
	// prologue already states; the inventory lists third-party packages only.
	ownModule = "github.com/ovumcy/ovumcy-web"
)

// unknownOverrides records the packages go-licenses cannot classify, with the
// classification a human made by reading the license file. A row is consulted
// only when the report says Unknown, so a later go-licenses release that
// learns to classify one of these simply stops consulting it.
var unknownOverrides = map[string]struct{ url, license string }{
	// Standard BSD-3-Clause text; go-licenses fails on the LICENSE layout.
	"modernc.org/mathutil": {url: "https://gitlab.com/cznic/mathutil/-/blob/master/LICENSE", license: "BSD-3-Clause"},
}

func main() {
	write := flag.Bool("write", false, "rewrite the generated block in "+inventoryPath)
	check := flag.Bool("check", false, "verify the generated block matches the report on stdin")
	flag.Parse()
	if *write == *check {
		fmt.Fprintln(os.Stderr, "licensesdoc: pass exactly one of -write or -check")
		os.Exit(2)
	}

	table, err := tableFromReport(bufio.NewScanner(os.Stdin))
	if err != nil {
		fmt.Fprintf(os.Stderr, "licensesdoc: %v\n", err)
		os.Exit(1)
	}

	document, err := os.ReadFile(inventoryPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "licensesdoc: %v\n", err)
		os.Exit(1)
	}
	updated, current, err := replaceBlock(string(document), table)
	if err != nil {
		fmt.Fprintf(os.Stderr, "licensesdoc: %v\n", err)
		os.Exit(1)
	}

	if *check {
		if current != table {
			fmt.Fprintf(os.Stderr, "licensesdoc: %s is stale — regenerate it:\n\n    go run github.com/google/go-licenses@v1.6.0 report ./cmd/ovumcy | go run ./scripts/licensesdoc -write\n\n%s\n", inventoryPath, diffSummary(current, table))
			os.Exit(1)
		}
		fmt.Println("licensesdoc: inventory matches the dependency report.")
		return
	}
	if err := os.WriteFile(inventoryPath, []byte(updated), 0o644); err != nil {
		fmt.Fprintf(os.Stderr, "licensesdoc: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("licensesdoc: wrote the generated block in %s.\n", inventoryPath)
}

// tableFromReport turns go-licenses CSV rows (package,url,license) into the
// markdown table body, sorted by package path.
func tableFromReport(scanner *bufio.Scanner) (string, error) {
	rows := make([]string, 0, 64)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		fields := strings.Split(line, ",")
		if len(fields) != 3 {
			return "", fmt.Errorf("malformed report line (want 3 comma-separated fields): %q", line)
		}
		pkg, url, license := fields[0], strings.ReplaceAll(fields[1], `\`, "/"), fields[2]
		if pkg == ownModule || strings.HasPrefix(pkg, ownModule+"/") {
			continue
		}
		if license == "Unknown" {
			override, ok := unknownOverrides[pkg]
			if !ok {
				return "", fmt.Errorf("go-licenses cannot classify %q and no override is recorded — read its license file and add one", pkg)
			}
			url, license = override.url, override.license
		}
		rows = append(rows, fmt.Sprintf("| `%s` | %s | [license text](%s) |", pkg, license, url))
	}
	if err := scanner.Err(); err != nil {
		return "", err
	}
	if len(rows) == 0 {
		return "", fmt.Errorf("the report on stdin is empty — run go-licenses report ./cmd/ovumcy and pipe its output in")
	}
	sort.Strings(rows)
	return "| Package | License | Text |\n| --- | --- | --- |\n" + strings.Join(rows, "\n"), nil
}

// replaceBlock swaps the text between the markers for table, returning the
// updated document and the block it replaced.
func replaceBlock(document, table string) (updated, current string, err error) {
	start := strings.Index(document, beginMarker)
	end := strings.Index(document, endMarker)
	if start < 0 || end < 0 || end < start {
		return "", "", fmt.Errorf("%s does not carry the BEGIN/END generated-block markers", inventoryPath)
	}
	head := document[:start+len(beginMarker)]
	tail := document[end:]
	current = strings.TrimSpace(document[start+len(beginMarker) : end])
	updated = head + "\n" + table + "\n" + tail
	return updated, current, nil
}

// diffSummary names the rows present on one side only — enough to see which
// dependency moved without a real diff tool.
func diffSummary(current, want string) string {
	currentRows := map[string]bool{}
	for row := range strings.SplitSeq(current, "\n") {
		currentRows[row] = true
	}
	wantRows := map[string]bool{}
	var summary strings.Builder
	for row := range strings.SplitSeq(want, "\n") {
		wantRows[row] = true
		if !currentRows[row] {
			summary.WriteString("  missing: " + row + "\n")
		}
	}
	for row := range strings.SplitSeq(current, "\n") {
		if !wantRows[row] {
			summary.WriteString("  stale:   " + row + "\n")
		}
	}
	return strings.TrimRight(summary.String(), "\n")
}
